add daemon mode and change install script

diff --git a/build/build b/build/build
--- a/build/build
+++ b/build/build
@@ -28,6 +28,9 @@ while [[ "$1" != "" ]]; do
             shift
             VERSION=$1
             ;;
+        -l|--latest)
+            LATEST=1
+            ;;
         -h|--help)
             cat <<EOT
 
@@ -49,6 +52,7 @@ OPTIONS:
                             be used.
     -r, --release <version> defines the release version. Version must be in the form vX.Y.Z[suffix]
                             where X, Y and Z an numbers. Visit https://semver.org/
+    -l, --latest            put into latest version the same context as for the release version
     -u, --upload            allows to upload the artifacts to S3
     -h, --help              prints the help
 
@@ -56,7 +60,7 @@ EOT
             exit 0
             ;;
         *)
-            echo "Unknown argument $1 passed! Try --help ..."
+            echo "Error: Unknown argument $1 passed! Try --help ..."
             exit 1
             ;;
     esac
@@ -64,13 +68,18 @@ EOT
 done
 
 if [[ -z ${VERSION} ]]; then
-    echo "release version must be provided e.g. 'build --release v1.2.3'  or you can try 'build --help' as well"
+    echo "Error: release version must be provided e.g. 'build --release v1.2.3'  or you can try 'build --help' as well"
     exit 1
 fi
 
 if [[ ! ${VERSION} =~ ^v[0-9]+\.[0-9]+\.[0-9]+.* ]]; then
-    echo "release version must start with 'v' has <X.Y.Z> format and an optional suffix. E.g. v1.3.123-test"
+    echo "Error: release version must start with 'v' has <X.Y.Z> format and an optional suffix. E.g. v1.3.123-test"
     exit 1
+fi
+
+if [ -n "$(git status --porcelain)" ]; then
+    UNCOMMITED=$(git rev-parse --abbrev-ref HEAD)
+    echo "Warning: found uncommited changes on the branch ${UNCOMMITED}"
 fi
 
 echo "Creating temporary dir for building artficats."
@@ -107,6 +116,11 @@ else
     if [[ -z ${BRANCH} ]]; then
         BRANCH=$(git rev-parse --abbrev-ref HEAD)
         check $?
+    fi
+
+    if [[ "${UNCOMMITED}" == "${BRANCH}" ]]; then
+        echo "Error: there are uncommited changes on the branch ${BRANCH}, could not making release out of there yet."
+        exit 1
     fi
 
     echo "There is no tag $VERSION. Will build the product for latest known commit from ${BRANCH}, and tag it by the version, if the build is successful."
@@ -173,6 +187,11 @@ if [[ ! -z $BRANCH ]]; then
     git tag $VERSION
     git push origin $VERSION
     check $?
+fi
+
+if [[ ! -z ${LATEST} ]]; then
+    echo "copy context of ${SRC_PATH}/binaries/${VERSION} to ${SRC_PATH}/binaries/latest"
+    cp -r ${SRC_PATH}/binaries/${VERSION} ${SRC_PATH}/binaries/latest
 fi
 
 if [[ ! -z ${UPLOAD} ]]; then
diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,20 +2,55 @@
 
 function error {
     msg=$1
-    echo "ERROR! ${msg}"
+    echo "Error: ${msg}"
     exit 1
 }
 
 ################# Main #################
+CMD="lr"
+VERSION="latest"
+DEST="/usr/local/bin"
 
-CMD=$1
-if [[ -z ${CMD} ]]; then
-    CMD="lr"
+if [[ "$1" == "logrange" || "$1" == "lr" ]]; then
+    CMD=$1
+    shift
 fi
 
-if [[ "${CMD}" != "logrange" && "${CMD}" != "lr" ]]; then
-    error "Command '${CMD}' does not exist!"
-fi
+while [[ "$1" != "" ]]; do
+    case $1 in
+        -r|--release)
+            shift
+            VERSION=$1
+            ;;
+        -d|--dest)
+            shift
+            DEST=$1
+            ;;
+        -h|--help)
+            cat <<EOT
+
+USAGE: install [lr|logrange] [options]
+
+    install allows to download 'logrange' (server) or 'lr' (client) command
+    and copy it into specified place. install expects the command name (lr|logrange)
+    which is optional. Default command is 'lr'
+
+OPTIONS:
+    -d, --dest <dir>    allows to specify the destination where the command
+                        will be copied. Default value is '/usr/local/bin'
+    -r, --release <ver> specifies the version for the downloaded command. The
+                        version must be in the form vX.Y.Z[suffix] or 'latest'
+    -h, --help          prints the help
+
+EOT
+            exit 0
+            ;;
+         *)
+            error "Unknown argument $1 passed! Try to run 'install --help' ..."
+            ;;
+    esac
+    shift
+done
 
 OS=$(uname)
 if [[ "${OS}" == "Linux" ]]; then
@@ -31,15 +66,24 @@ if [[ "$ARCH" != "x86_64" ]]; then
     error "Architecture '${ARCH}' is not supported!"
 fi
 
-URL=http://get.logrange.io/binaries/master/${OS}/${ARCH}/${CMD}
-echo "Downloading from ${URL}..."
+cd ${DEST}
+if [[ $? -ne 0 ]]; then
+    error "Could not change dir to '${DEST}', please check permissions and whether the dir exists"
+fi
+
+DEST=$(pwd)
+
+URL=http://get.logrange.io/binaries/${VERSION}/${OS}/${ARCH}/${CMD}
+echo "Downloading from ${URL} to ${DEST} ..."
 
 curl -sOfL ${URL}
 if [[ $? -ne 0 ]]; then
-    error "Failed downloading '${CMD}', please check URL and retry..."
+    error "Failed downloading '${CMD}', please check params and retry..."
 fi
 
 chmod +x ${CMD}
-mv ./${CMD} /usr/local/bin
-echo "Done! Try running '${CMD}'..."
+if [[ $? -ne 0 ]]; then
+    error "Could not make '${CMD}' executable, please check permissions"
+fi
+echo "Done! Try running '${DEST}/${CMD} --help'"
 
